### ISSUE TITLE
memory.x is wrong for microbit v2

### ISSUE THREAD

**Issue by romanstingler** [t4p-community/20241003_rust-on-bare-metal#1]
I didn't want to create an MR, as I have forked this repo and changed more things (updated the packages), deleted the `build.rs` (as it is not necessary on my system), used `panic-halt` crate. 
https://github.com/romanstingler/20241003_rust-on-bare-metal/commits/main/

but the microbit v2 has 
Flash ROM 	512KB
RAM 	        128KB
https://tech.microbit.org/hardware/

which should be 
```
MEMORY
{
  FLASH : ORIGIN = 0x00000000, LENGTH = 512K
  RAM : ORIGIN = 0x20000000, LENGTH = 128K
}
```

hardware version 1.3 and 1.5 had 
Flash ROM 	256KB
RAM 	          16KB

**Comment by ericwgreene** [comment]
Thank you for catching this! I will update it! I really appreciate it!

**Comment by ericwgreene** [comment]
I have updated the `memory.x` files and the documentation.

**Comment by t4p-community** [comment]
Thank you for catching this! I will update it! I really appreciate it!

I have updated the memory.x files and the documentation.

**Comment by t4p-community** [comment]
Thank you for catching this! I will update it! I really appreciate it!

I have updated the memory.x files and the documentation.
